import slugify from '../utils/slugify'

export default {
  title: "Blog",
  name: 'blog',
  type: "document",
  fields: [
    {
      title: "Title",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Author",
      name: "author",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: 'Published date',
      name: 'publishedDate',
      type: 'date',
      options: {
        dateFormat: 'DD MMMM YYYY',
      }
    },
    {
      title: "Image",
      name: "image",
      type: "defaultImage",
      validation: Rule => Rule.required()
    },
    {
      title: 'Content',
      name: 'newContent',
      type: 'blockContentExtended',
      validation: Rule => Rule.required()
    },
    // {
    //   title: 'Content',
    //   name: 'content',
    //   type: 'array', 
    //   of: [{type: 'block'}],
    //   validation: Rule => Rule.required()
    // },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          return `${doc.title}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`)
      },
      validation: Rule => Rule.required()
    },
  ],
  preview: {
    select: {
      title: 'title',
      lastName: 'lastName',
      image: 'image',
    },
    prepare(selection) {
      const {title, image} = selection
      return {
        title: `${title}`,
        media: image
      }
    }
  }
}